[package]
name = "basic_trie"
version = "1.0.1"
edition = "2021"
authors = ["LukasCobbler"]
license-file = "LICENSE"
readme = "README.md"
keywords = ["trie"]
description = "A simple Trie implementation in Rust"
repository = "https://github.com/lukascobbler/basic_trie"
documentation = "https://docs.rs/basic_trie/"

[dependencies]
unicode-segmentation = { version = "1.10.*", optional = true }

[features]
default = ["unicode"]
unicode = ["unicode-segmentation"]